export const nodeDataArrayPalette = [
  {
    key: "cat",
    text: "1",
    figure: "Rectangle",
    color: "lightblue",
    source: "img/cat.png",
  },
  {
    key: "icon1",
    text: "2",
    figure: "Rectangle",
    background: "lightblue",
    source: "img/icon1.png",
  },
  {
    key: "icon2",
    text: "3",
    figure: "Rectangle",
    color: "lightblue",
    source: "img/icon2.png",
  },
  {
    key: "cat2",
    text: "4",
    figure: "Rectangle",
    color: "lightblue",
    source: "img/cat2.png.jpg",
  },
  {
    key: "cat3",
    text: "5",
    figure: "Rectangle",
    color: "lightblue",
    source: "img/cat3.png.jpg",
  },
  {
    key: "rainbow",
    text: "6",
    figure: "Rectangle",
    color: "lightblue",
    source: "img/rainbow.png.jpg",
  },
  {
    key: "Group1",
    text: "7",
    figure: "Rectangle",
    color: "lightblue",
    fill: null,
  },
];